import './globals.css'
import 'regenerator-runtime/runtime'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        // className={inter.className}
        className='w-full bg-black lg:inline'
      >
        {children}
        <Footer />
      </body>
    </html>
  )
}
