version: '3.8'

services:
  postgres:
    image: 'postgres:14.1-alpine'
    restart: always
    env_file:
      - .env
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7.0.11-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./volume/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 5s

  backend:
    build: "./backend"
    env_file:
      - .env
    environment:
      - port=8000
    volumes:
      - ./backend/app:/app
      - ./backend/migrations:/migrations
      - ./backend/_data:/_data
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
