{
 "title": "FastAPIObservability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "ApplicationName",
    "query": {
     "query": "label_values(fastapi_app_info{},app_name)"
    }
   },
   { "name": "log_keyword", "label": "LogQuery" }
  ]
 },
 "panels": [
  {
   "title": "TotalRequests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fastapi_requests_total{app_name=\"$app_name\",path!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "RequestsCount",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_requests_total{app_name=\"$app_name\",path!=\"/metrics\"}",
     "legendFormat": "{{method}}{{path}}"
    }
   ]
  },
  {
   "title": "RequestsAverageDuration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_requests_duration_seconds_sum{app_name=\"$app_name\"}/fastapi_requests_duration_seconds_count{app_name=\"$app_name\"}",
     "legendFormat": "{{method}}{{path}}"
    }
   ]
  },
  {
   "title": "TotalExceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_exceptions_total{app_name=\"$app_name\"}"
    }
   ]
  },
  {
   "title": "Percentof2xxRequests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sumby(path)(fastapi_responses_total{app_name=\"$app_name\",status_code=~\"2.*\",path!=\"/metrics\"})/sumby(path)(fastapi_responses_total{app_name=\"$app_name\",path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percentof5xxRequests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sumby(path)(fastapi_responses_total{app_name=\"$app_name\",status_code=~\"5.*\",path!=\"/metrics\"})/sumby(path)(fastapi_responses_total{app_name=\"$app_name\",path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PR99RequestsDuration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(fastapi_requests_duration_seconds_bucket{app_name=\"$app_name\",path!=\"/metrics\"}[1m]))by(path,le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "RequestInProcess",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "fastapi_requests_in_progress{app_name=\"$app_name\",path!=\"/metrics\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "RequestPerSec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(fastapi_requests_total{app_name=\"$app_name\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "LogTypeRate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sumby(type)(rate({compose_service=~\"app-.*\"}|pattern`<date><time><type><logger><code>[<_>=<trace_id><_>=<span_id><_>=<service_name>]-<msg>`|type!=\"\"|=\"$log_keyword\"[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "LogofAllFastAPIApp",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "{compose_service=~\"app-.*\"}|pattern`<date><time><type><logger><code>[<_>=<trace_id><_>=<span_id><_>=<service_name>]-<msg>`|line_format\"{{.compose_service}}\\t{{.type}}\\ttrace_id={{.trace_id}}\\t{{.msg}}\"|=\"$log_keyword\""
    }
   ]
  }
 ]
}